---
title: "Lab 06 - Functions and iterations"
author: "Andrew Morris"
date: "`r Sys.Date()`"
output: html_document
---


### Packages and Data

```{r load-packages, message=FALSE}
library(tidyverse) 
library(ggplot2)
```

```{r diamon_rename}
diamonds <- diamonds %>% rename(
    depth_pct = depth,
    length_mm = x,
    width_mm = y,
    depth_mm = z,
    table_pct = table
  )
```


## Exercise 1

```{r}
# Do some preliminary investigations & cleaning


diamonds %>%
   ggplot(mapping = aes(x = carat)) +
      geom_histogram(binwidth = 0.05)

# diamonds %>%
#   ggplot(mapping=aes(x=cut, y=price)) +
#   geom_dotplot()

diamonds <- diamonds %>% 
  filter(length_mm!=0 & width_mm!=0 & depth_mm!=0)

view(diamonds)
```


## Exercise 2

```{r}

diamonds <- diamonds %>%
  mutate(table_mm = ((table_pct * width_mm) / 100))

view(diamonds)

# Overall table_mm arithmetic mean?

diamonds %>% summarise(arithmetic_mean_tablemm = mean(table_mm))




# table_mm arithmetic mean within each clarity category

diamonds %>%
  group_by(clarity) %>%
  summarise(arithmetic_mean = mean(table_mm))



```

As the clarity goes up so does the arithmetic mean of the table mm

```{r}
# calculate the arithmetic mean across all numeric variables

diamonds %>% 
  summarise(across(depth_pct:table_mm), mean, .names = "avg_{.col}")



```

## Exercise 3

```{r}
# Write gmean() command

gmean <- function(x){
  for (i in length(x)) {
    gx <- log(x[i])
  }
  gx <- exp((1/length(x))*gx)
}

```

## Exercise 4

```{r, error = TRUE}

test_data <- list(
  test1 = c(2.1, 3.8, 4.2),
  test2 = c(1, 10, 100, 1000),
  test3 = c(0, 1, 4),
  test4 = c(0.38,  0.94, -1.56),
  test5 = c(TRUE, TRUE),
  test6 = c("6", "7", "8")
)


# Create for loop to test gmean() on the above examples

gmean(test_data[1])

```


## Exercise 5

```{r}
# Copy gmean() from Ex 3 and edit it to check the input





# Copy your code from Ex 4 to test your new command





```

## Exercise 6

```{r}
# replicate the for loop from Ex 4 using the map (or a similar) function

```


## Exercise 7

```{r}
# Overall table_mm arithmetic mean, median, and geometric mean?






# Arithmetic mean, median, and geometric mean of table_mm within each clarity category






```

_Add your comment here_


## Exercise 8 (optional)

```{r}
# Create gmean2() that computes the geometric mean 
#   that uses the original definition






```


## Exercise 9 (optional)

```{r}
# Create a function that computes the harmonic mean







```

## Exercise 10 (optional)

_Do derivation on paper, unless you know how to write LaTeX code_
